// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98Q4tECHd8C0jdzyyJ4S94yD3WUEhDPU',
    appId: '1:703588825307:android:f52b18a20336eb148df4fe',
    messagingSenderId: '703588825307',
    projectId: 'reang-app',
    storageBucket: 'reang-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-pl-nJI0huy-kHUq5w2rJoXpR2wCmcJE',
    appId: '1:703588825307:ios:17a1ad4d63db4cc08df4fe',
    messagingSenderId: '703588825307',
    projectId: 'reang-app',
    storageBucket: 'reang-app.firebasestorage.app',
    iosBundleId: 'com.example.reangApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-pl-nJI0huy-kHUq5w2rJoXpR2wCmcJE',
    appId: '1:703588825307:ios:17a1ad4d63db4cc08df4fe',
    messagingSenderId: '703588825307',
    projectId: 'reang-app',
    storageBucket: 'reang-app.firebasestorage.app',
    iosBundleId: 'com.example.reangApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrG-ogKiERy73yyfSXosBZFeG5DJb6RfM',
    appId: '1:703588825307:web:aa6ded54da5106588df4fe',
    messagingSenderId: '703588825307',
    projectId: 'reang-app',
    authDomain: 'reang-app.firebaseapp.com',
    storageBucket: 'reang-app.firebasestorage.app',
    measurementId: 'G-L50PJ4GLZB',
  );
}
